// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/KFSMLE_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FastOptim
Results FastOptim(NumericVector startR, NumericMatrix XR, NumericVector tauR, int m, int d, double xtol, double stop_val, int algorithm_id, bool hessian, double step_size, bool log);
RcppExport SEXP _KFSMLE_FastOptim(SEXP startRSEXP, SEXP XRSEXP, SEXP tauRSEXP, SEXP mSEXP, SEXP dSEXP, SEXP xtolSEXP, SEXP stop_valSEXP, SEXP algorithm_idSEXP, SEXP hessianSEXP, SEXP step_sizeSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type startR(startRSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XR(XRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tauR(tauRSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type xtol(xtolSEXP);
    Rcpp::traits::input_parameter< double >::type stop_val(stop_valSEXP);
    Rcpp::traits::input_parameter< int >::type algorithm_id(algorithm_idSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(FastOptim(startR, XR, tauR, m, d, xtol, stop_val, algorithm_id, hessian, step_size, log));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KFSMLE_FastOptim", (DL_FUNC) &_KFSMLE_FastOptim, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_KFSMLE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
