# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SPDX-License-Identifier: GPL-3.0-or-later */
#'
#' Copyright (c) 2025 Domenic Franjic
#'
#' This file is part of QuoteDynamics.
#'
#' QuoteDynamics is free software: you can redistribute it
#' and/or modify it under the terms of the GNU General Public License
#' as published by the Free Software Foundation, either version 3
#' of the License, or (at your option) any later version.
#'
#' QuoteDynamics is distributed in the hope that it will be useful,
#' but WITHOUT ANY WARRANTY; without even the implied warranty
#' of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#' See the GNU General Public License for more details.
#'
#' You should have received a copy of the GNU General Public License
#' along with QuoteDynamics.  If not, see <https://www.gnu.org/licenses/>.
#' @docType package
#' @name QuoteDynamics
NULL

#' FastOptim Function
#'
#' Fast KFS MLE implementation
#'
#' @param startR Starting values
#' @param XR Data Matrix
#' @param tauR Parameter vector
#' @param ind_matrix_R Identifier matrix
#' @param xtol Algorithm tolerance
#' @param stop_val Stopping rule
#' @return Returns minimum value (changes start in place)
#' @export
FastOptim <- function(startR, XR, tauR, ind_matrix_R, xtol, stop_val, max_eval, algorithm_id, hessian, step_size, log) {
    .Call('_QuoteDynamics_FastOptim', PACKAGE = 'QuoteDynamics', startR, XR, tauR, ind_matrix_R, xtol, stop_val, max_eval, algorithm_id, hessian, step_size, log)
}

