# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SPDX-License-Identifier: GPL-3.0-or-later */
#'
#' Copyright (c) 2025 Domenic Franjic
#'
#' This file is part of QuoteDynamics.
#'
#' QuoteDynamics is free software: you can redistribute it
#' and/or modify it under the terms of the GNU General Public License
#' as published by the Free Software Foundation, either version 3
#' of the License, or (at your option) any later version.
#'
#' QuoteDynamics is distributed in the hope that it will be useful,
#' but WITHOUT ANY WARRANTY; without even the implied warranty
#' of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#' See the GNU General Public License for more details.
#'
#' You should have received a copy of the GNU General Public License
#' along with QuoteDynamics.  If not, see <https://www.gnu.org/licenses/>.
#' @docType package
#' @name QuoteDynamics
NULL

#'  Wrapper to compute the neg-log-like ought to be called from within R for usage with Rs optim()
#'
#' @param n Size of the paramter vector
#' @param x Pointer to the data of the parameter vector
#' @param grad Pointer to the data of the gradient
#' @param data Pointer to the data structure that holds additional function parameters of the actual objective function
#' @return Objective function value of the current parameter estimate
#' @export
objFunctionCpp <- function(startR, XR, tauR, ind_matrix_R, day_indicator_R, initial_kf_var_cov, log) {
    .Call('_QuoteDynamics_objFunctionCpp', PACKAGE = 'QuoteDynamics', startR, XR, tauR, ind_matrix_R, day_indicator_R, initial_kf_var_cov, log)
}

#' FastOptim Function
#'
#' Fast KFS MLE implementation
#'
#' @param startR Starting values
#' @param XR Data Matrix
#' @param tauR Parameter vector
#' @param ind_matrix_R Identifier matrix
#' @param rel_xtol Algorithm tolerance
#' @param rel_ftol Stopping rule
#' @param algorithm_id NLopt algorithm ID
#' @param upper_bound_R Upper parameter bounds (only for global optimisers)
#' @param lower_bound_R Lower parameter bounds (only for global optimisers)
#' @param initial_kf_var_cov Initial Kalman filter state variance
#' @param compute_se Whether or not standard eroors should be computed
#' @param no_of_bootstraps Number of bootstrap repititions
#' @param length_of_bootstraps Length of each bootstrap block
#' @param seed Seed used for bootstrapping
#' @param hessian Whether or not to compute the hessian
#' @param step_size Step size for the computation of the hessian
#' @param log Whether or not to print output
#' @return Returns optimisation object
#' @export
FastOptim <- function(startR, XR, tauR, ind_matrix_R, day_indicator_R, rel_xtol, rel_ftol, max_eval, algorithm_id, upper_bound_R, lower_bound_R, initial_kf_var_cov, compute_se, no_of_bootstraps, length_of_bootstraps, seed, hessian, step_size, log) {
    .Call('_QuoteDynamics_FastOptim', PACKAGE = 'QuoteDynamics', startR, XR, tauR, ind_matrix_R, day_indicator_R, rel_xtol, rel_ftol, max_eval, algorithm_id, upper_bound_R, lower_bound_R, initial_kf_var_cov, compute_se, no_of_bootstraps, length_of_bootstraps, seed, hessian, step_size, log)
}

