# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FastOptim Function
#'
#' Fast KFS MLE implementation
#'
#' @param startR Starting values
#' @param XR Data Matrix
#' @param tauR Parameter vector
#' @param xtol Algorithm tolerance
#' @param stop_val Stopping rule
#' @return Returns minimum value (changes start in place)
#' @export
FastOptim <- function(startR, XR, tauR, xtol, stop_val, algorithm_id, hessian, step_size, log) {
    .Call('_QuoteDynamics_FastOptim', PACKAGE = 'QuoteDynamics', startR, XR, tauR, xtol, stop_val, algorithm_id, hessian, step_size, log)
}

